app/src/main/java/com/example/planetze/MainActivity.java
=> fix: fixed MainActivity crash behavior

app/build.gradle.kts, app/src/main/java/com/example/planetze/LoginActivity.java, app/src/main/java/com/example/planetze/MainActivity.java, app/src/main/java/com/example/planetze/classes/LoginManager.java, app/src/main/java/com/example/planetze/ui/login/IOnSelectionListener.java, app/src/main/java/com/example/planetze/ui/login/Login/Contract.java, app/src/main/java/com/example/planetze/ui/login/Login/LoginFragment.java, app/src/main/java/com/example/planetze/ui/login/Login/LoginPresenter.java, app/src/main/java/com/example/planetze/ui/login/LoginOptionFragment.java, app/src/main/java/com/example/planetze/ui/login/Register/RegisterFragment.java, app/src/main/java/com/example/planetze/ui/login/ResetPassword/ResetPasswordFragment.java, app/src/main/res/layout/fragment_register.xml, app/src/test/java/com/example/planetze/LoginTest.java, gradle/libs.versions.toml
Modified Login feature to M-V-P Model
Added Mockito test cases for Login
=> test: added Mockito testcases for Login

app/src/main/java/com/example/planetze/classes/LoginManager.java, app/src/main/java/com/example/planetze/ui/login/Login/Contract.java, app/src/main/java/com/example/planetze/ui/login/Login/LoginFragment.java, app/src/main/java/com/example/planetze/ui/login/Login/LoginPresenter.java, app/src/main/java/com/example/planetze/ui/login/Register/RegisterFragment.java, app/src/main/java/com/example/planetze/ui/login/ResetPassword/ResetPasswordFragment.java, app/src/test/java/com/example/planetze/LoginTest.java
Added confirmation email feature for user registration
=> Fix/plan 7/login with confirmation email

app/src/main/java/com/example/planetze/classes/LoginManager.java, app/src/main/java/com/example/planetze/ui/login/Login/Contract.java, app/src/main/java/com/example/planetze/ui/login/Login/LoginFragment.java, app/src/main/java/com/example/planetze/ui/login/Login/LoginPresenter.java, app/src/test/java/com/example/planetze/LoginTest.java
Added email verification feature
Fixed bug where user stay logged in, and email is not sent
=> Feature/plan 15/day selection

app/src/main/java/com/example/planetze/HabitSelectionActivity.java, app/src/main/java/com/example/planetze/classes/User.java
=> feat:added habit recommendation

app/src/main/java/com/example/planetze/ui/eco_tracker/main/ShowActivityFragment.java, app/src/main/res/layout/fragment_show_activity.xml
Fixed black color for the edittext (pickADate)
Piechart updates every time data changes
=> fix: pie chart get update when data changed

app/src/main/java/com/example/planetze/LoginActivity.java, app/src/main/java/com/example/planetze/MainActivity.java, app/src/main/java/com/example/planetze/classes/EcoTracker/Category/Consumption/EnergyBill.java
Fixed bug where screen crashed when relogin
Added typeId for Energy Bill
=> fix: fixed bug where screen crashed when relogin

app/src/main/java/com/example/planetze/HabitSelectionActivity.java, app/src/main/java/com/example/planetze/classes/EcoTracker/Habit/RecyclerAdaptor.java, app/src/main/res/layout/activity_habit_selection.xml
Removed scrolling screen when selecting habit to adopt, allows smoother interaction with app.
=> Bugfix/plan 17/adopt habits

app/src/main/java/com/example/planetze/HabitSelectionActivity.java, app/src/main/java/com/example/planetze/LogHabitActivity.java, app/src/main/java/com/example/planetze/ui/eco_tracker/ActivityListFragment.java, app/src/main/java/com/example/planetze/ui/eco_tracker/main/ShowActivityFragment.java, app/src/main/res/layout/activity_habit_selection.xml, app/src/main/res/layout/fragment_activity_list.xml
Added back button
Fixed log habit button UI
=> fix: fixed buttons UI and added back button

app/src/main/java/com/example/planetze/classes/EcoTracker/Category/Transportation/CarType/Car.java, app/src/main/java/com/example/planetze/classes/ScreenUtilities/ViewGenerator.java, app/src/main/java/com/example/planetze/ui/eco_tracker/BaseActivityFragment.java, app/src/main/java/com/example/planetze/ui/eco_tracker/BuyElectronicsFragment.java, app/src/main/java/com/example/planetze/ui/eco_tracker/BuyNewClothesFragment.java, app/src/main/java/com/example/planetze/ui/eco_tracker/CyclingOrWalkingFragment.java, app/src/main/java/com/example/planetze/ui/eco_tracker/DrivePersonalVehicleFragment.java, app/src/main/java/com/example/planetze/ui/eco_tracker/EnergyBillsFragment.java, app/src/main/java/com/example/planetze/ui/eco_tracker/FlightFragment.java, app/src/main/java/com/example/planetze/ui/eco_tracker/MealFragment.java, app/src/main/java/com/example/planetze/ui/eco_tracker/OtherPurchasesFragment.java, app/src/main/java/com/example/planetze/ui/eco_tracker/TakePublicTransportationFragment.java, app/src/main/java/com/example/planetze/ui/eco_tracker/main/EcoTrackerFragment.java
Fixed edit feature
Fixed the transition between edit <-> main, add <-> add2 -> main
- [] My changes generate no new warnings
=> Bugfix/no ref/fix edit navigation

app/src/main/java/com/example/planetze/classes/EcoTracker/Date.java, app/src/main/java/com/example/planetze/ui/eco_gauge/EcoGaugeFragment.java, app/src/main/res/layout/fragment_eco_gauge.xml, app/src/main/res/values/colors.xml
=> feat: added feature eco gauge

app/src/main/java/com/example/planetze/classes/ScreenUtilities/StringHandler.java, app/src/main/java/com/example/planetze/classes/ScreenUtilities/ViewGenerator.java, app/src/main/java/com/example/planetze/ui/profile/ProfileConstants.java, app/src/main/java/com/example/planetze/ui/profile/ProfileFragment.java
Added StringHandler
Profile now has max characters it can display
=> feat: added StringHandler.java to handle String related item

app/src/main/java/com/example/planetze/ui/eco_balance/EcoBalanceFragment.java
Handled empty input for carbon credit
=> fix: handled empty input for $

app/src/main/java/com/example/planetze/FormResultActivity.java, app/src/main/java/com/example/planetze/MainActivity.java, app/src/main/java/com/example/planetze/classes/AnnualEmission/AnnualEmissionCalculator.java, app/src/main/java/com/example/planetze/classes/ScreenUtilities/StringHandler.java, app/src/main/java/com/example/planetze/classes/User.java, app/src/main/java/com/example/planetze/classes/UserDatabaseManager.java, app/src/main/java/com/example/planetze/ui/eco_tracker/main/EcoTrackerFragment.java, app/src/main/java/com/example/planetze/ui/profile/ProfileFragment.java
Fixed bug where data are deleted after relogin
=> fix: fix data lost when relogin

app/src/main/res/layout/activity_form_result.xml, app/src/main/res/values/strings.xml
- modified form result UI design
=> fix: modified form result UI design

app/build.gradle.kts, app/src/main/java/com/example/planetze/classes/AnnualEmission/AnnualEmissionCalculator.java, app/src/main/java/com/example/planetze/classes/EcoTracker/ActivitiesCalculator.java, app/src/main/java/com/example/planetze/classes/EcoTracker/Date.java, app/src/main/java/com/example/planetze/ui/eco_gauge/EcoGaugeFragment.java, app/src/main/java/com/example/planetze/ui/eco_tracker/main/EcoTrackerFragment.java, app/src/main/res/layout/fragment_eco_gauge.xml, gradle.properties, gradle/libs.versions.toml
=> Feature/plan 22/line graph

app/src/main/res/layout/card_view.xml, app/src/main/res/layout/fragment_eco_tracker.xml, app/src/main/res/layout/fragment_habit_selection.xml
- fixed habit UI design
- fixed activity management UI design
=> Fix/no ref/modified UI design

app/src/main/java/com/example/planetze/classes/EcoTracker/EcoTrackerEmissionConstant.java, app/src/main/java/com/example/planetze/classes/GlobalAverages.java, app/src/main/java/com/example/planetze/ui/eco_gauge/EcoGaugeFragment.java, app/src/main/java/com/example/planetze/ui/profile/ProfileFragment.java, app/src/main/res/layout/fragment_eco_gauge.xml, app/src/main/res/values/strings.xml
Disabled the description of line graph
Fixed error in global averages calculations
=> fix: fixed wrong calculation on eco gauge

app/src/main/res/layout/fragment_eco_gauge.xml, app/src/main/res/values/colors.xml
- modified Eco Gauge UI design
=> fix: modified Eco Gauge UI design

app/src/main/java/com/example/planetze/FormResultActivity.java
Used tons instead of kg for the annual carbon footprints calculation.
=> fix: changed kg to ton
